version: '3'

vars:
  REPO_NAME: varia
  REPO_BASE_DIR: 'repo'
  ARCH: 'x86_64'
  REPO_DIR: "{{.REPO_BASE_DIR}}/{{.ARCH}}"
  PACKAGE_GLOB: "*.pkg.tar.zst"

tasks:
  update-repo:
    desc: "Update the local package repository with new packages and sign it."
    cmds:
      - 'echo "Starting repository update for {{.REPO_NAME}} (Arch: {{.ARCH}}) in {{.REPO_DIR}}..."'
      - repo-add --verify --sign -n {{.REPO_DIR}}/{{.REPO_NAME}}.db.tar.gz {{.REPO_DIR}}/{{.PACKAGE_GLOB}} --key=FD8F04B290F3E2FD18CDAF9FD53A3E0AB76602CF
      - echo "Repository update complete."
      - ls -l {{.REPO_DIR}}/{{.REPO_NAME}}.db.tar.gz*
      - git add .
      - git commit -m "update pkgs"
  clean-signatures:
    desc: "Remove existing repository signature files (Use with caution)."
    cmds:
      - rm -f {{.REPO_DIR}}/{{.REPO_NAME}}.db.tar.gz.sig
      - echo "Existing signatures removed."
      - git add .
      - git commit -m "remove signatures"